<?php

/**
 * PluginsfSimpleForumRankTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfSimpleForumRankTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfSimpleForumRankTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfSimpleForumRank');
    }
}