<?php

/**
 * PluginsfSimpleForumRecommandationLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfSimpleForumRecommandationLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfSimpleForumRecommandationLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfSimpleForumRecommandationLog');
    }
}