<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfSimpleForumTopicTable extends Doctrine_Table
{
  public function setIsNewForUser($topics, $user_id)
  {
    $topic_ids  = array();
    $topic_hash = array();
    foreach ($topics as $topic)
    {
      // A topic is new unless we can find a view from the user for it
      $topic->setIsNew(true);
      $id = $topic->getId();
      $topic_ids[] = $id;
      $topic_hash[$id] = $topic;
    }
    //print_r(array_keys($topic_hash));
    
    $q = $this->createQuery();
    $q->leftJoin('sfSimpleForumTopic.sfSimpleForumTopicView tv');
    $q->whereIn('tv.topic_id', $topic_ids);
    $q->where('tv.user_id = ?', array($user_id));
    $rs = $q->execute();
    
    foreach($rs as $oneTopic)
    {
      $tv = $oneTopic->get('sfSimpleForumTopicView');
      if(isset($topic_hash[$tv[0]->get('topic_id')]))
      {
        $topic = $topic_hash[$tv[0]->get('topic_id')];
        $topic->setIsNew(false);
      }
    }
    
    return $topic_hash;
  }
  
  public function getLatestCriteria()
  {
    $q = $this->createQuery();
    $q->orderBy('updated_at DESC');
    
    return $q;
  }  
  
  public function getLatest($max = 10)
  {
    $q = $this->getLatestCriteria();
    $q->limit($max);
    
    return $q->execute();
  }
  
  public function getLatestPager($page = 1, $max_per_page = 10)
  {
    $q = $this->getLatestCriteria();
    $pager = new sfDoctrinePager('sfSimpleForumTopic', $max_per_page);
    $pager->setPage($page);
    $pager->setQuery($q);
    $pager->init();
    
    return $pager;
  }
  
  public function getForUserCriteria($user_id)
  {
    $q = $this->createQuery();
    $q->where('user_id = ?', array($user_id));
    $q->orderBy('updated_at DESC');
    
    return $q;
  }  
  
  public function getForUser($user_id, $max = 10)
  {
    $q = $this->getForUserCriteria($user_id);
    $q->limit($max);
    
    return $this->doSelectJoinAll($c);
  }
  
  public function getForUserPager($user_id, $page = 1, $max_per_page = 10)
  {
    $q = $this->getForUserCriteria($user_id);
    $pager = new sfDoctrinePager('sfSimpleForumTopic', $max_per_page);
    $pager->setPage($page);
    $pager->setQuery($q);
    $pager->init();
    
    return $pager;
  }
  
  public function countForUser($user_id)
  {
    $q = $this->createQuery();
    $q->where('user_id = ?', array($user_id));
    
    return $q->execute()->count();
  }
}