<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfSimpleForumPostTable extends Doctrine_Table
{
  public function getOneJoinForum($id)
  {
    $q = $this->createQuery();
    $q->where('id = ?', array($id));
    $object = $q->limit(1)->execute()->getFirst();

    if ($object instanceOf sfSimpleForumPost)
    {
      return $object;
    }
    return null;
  }

  public function getLatestCriteria()
  {
    $q = $this->createQuery();
    $q->orderBy('id DESC');

    return $q;
  }

  public function getLatest($max = null)
  {
    $q = $this->getLatestCriteria();
    if($max)
    {
      $q->limit($max);
    }

    return $q->execute();
  }

  public function getLatestPager($page = 1, $max_per_page = 10)
  {
    $q = $this->getLatestCriteria();
    $pager = new sfDoctrinePager('sfSimpleForumPost', $max_per_page);
    $pager->setPage($page);
    $pager->setQuery($q);
    //$pager->setPeerMethod('doSelectJoinsfSimpleForumForum');
    $pager->init();

    return $pager;
  }

  public function getForTopicCriteria($topic_id)
  {
    $q = $this->createQuery('t');
    $q->where('topic_id = ?', array($topic_id));

    return $q;
  }

  public function getForTopic($topic_id, $max = null)
  {
    $q = $this->getForTopicCriteria($topic_id);
    $q->orderBy('id DESC');
    if($max)
    {
      $q->limit($max);
    }

    return $q->execute();
  }

  public function getForTopicPager($topic_id, $page = 1, $max_per_page = 10)
  {
    $q = $this->getForTopicCriteria($topic_id)
      ->leftJoin('t.sfGuardUser u')
      ->leftJoin('u.sfSimpleForumPost upo')
      ->leftJoin('u.Permissions upe')
      ->leftJoin('u.Groups ug')
      ->orderBy('t.id ASC');

    $pager = new sfDoctrinePager('sfSimpleForumPost', $max_per_page);
    $pager->setPage($page);
    $pager->setQuery($q);
    $pager->init();

    return $pager;
  }

  public function getForForumCriteria($forum_name)
  {
    $q = $this->getLatestCriteria();
    $q->where('sfSimpleForumPost.sfSimpleForumForum.slug = ?', array($forum_name));

    return $q;
  }

  public function getForForum($forum_name, $max = null)
  {
    $q = $this->getForForumCriteria($forum_name);
    if($max)
    {
      $q->limit($max);
    }

    return $q->execute();
  }

  public function getForForumPager($forum_name = '', $page = 1, $max_per_page = 10)
  {
    $q = $this->getForForumCriteria($forum_name);

    $pager = new sfDoctrinePager('sfSimpleForumPost', $max_per_page);
    $pager->setPage($page);
    $pager->setQuery($q);
    //$pager->setPeerMethod('doSelectJoinsfSimpleForumForum');
    $pager->init();

    return $pager;
  }

  public function getForUserCriteria($user_id)
  {
    $q = $this->createQuery();
    $q->where('user_id = ?', array($user_id));
    $q->orderBy('id DESC');

    return $q;
  }

  public function getForUser($user_id, $max = null)
  {
    $q = $this->getForUserCriteria($user_id);
    if($max)
    {
      $q->limit($max);
    }

    return $q->execute();
  }

  public function getForUserPager($user_id, $page = 1, $max_per_page = 10)
  {
    $q = $this->getForUserCriteria($user_id);

    $pager = new sfDoctrinePager('sfSimpleForumPost', $max_per_page);
    $pager->setPage($page);
    $pager->setQuery($q);
    //$pager->setPeerMethod('doSelectJoinsfSimpleForumForum');
    $pager->init();

    return $pager;
  }

  public function countForUser($user_id)
  {
    $q = $this->createQuery();
    $q->where('user_id = ?', array($user_id));

    return $q->execute()->count();
  }




  /**
   * Selects a collection of sfSimpleForumPost objects pre-filled with related topic and forum objects.
   *
   * @return     array Array of sfSimpleForumPost objects.
   * @throws     PropelException Any exceptions caught during processing will be
   *             rethrown wrapped into a PropelException.
   */
  /* public function doSelectJoinTopicAndForum(Criteria $c, $con = null)
  {
    foreach (sfMixer::getCallables('BasesfSimpleForumPostPeer:doSelectJoinAllExcept:doSelectJoinAllExcept') as $callable)
    {
      call_user_func($callable, 'BasesfSimpleForumPostPeer', $c, $con);
    }

    $c = clone $c;

    if ($c->getDbName() == Propel::getDefaultDB())
    {
      $c->setDbName(self::DATABASE_NAME);
    }

    sfSimpleForumPostPeer::addSelectColumns($c);
    $startcol2 = (sfSimpleForumPostPeer::NUM_COLUMNS - sfSimpleForumPostPeer::NUM_LAZY_LOAD_COLUMNS) + 1;
    sfSimpleForumTopicPeer::addSelectColumns($c);
    $startcol3 = $startcol2 + sfSimpleForumTopicPeer::NUM_COLUMNS;
    sfSimpleForumForumPeer::addSelectColumns($c);
    $startcol4 = $startcol3 + sfSimpleForumForumPeer::NUM_COLUMNS;
    $c->addJoin(sfSimpleForumPostPeer::TOPIC_ID, sfSimpleForumTopicPeer::ID);
    $c->addJoin(sfSimpleForumPostPeer::FORUM_ID, sfSimpleForumForumPeer::ID);

    $rs = BasePeer::doSelect($c, $con);
    $results = array();

    while($rs->next())
    {
      $post = new sfSimpleForumPost();
      $post->hydrate($rs);

      $topic = new sfSimpleForumTopic();
      $topic->hydrate($rs, $startcol2);

      $newObject = true;
      foreach ($results as $temp_post)
      {
        $existing_topic = $temp_post->getsfSimpleForumTopic();
        if ($existing_topic->getPrimaryKey() === $topic->getPrimaryKey())
        {
          $newObject = false;
          $existing_topic->addsfSimpleForumPost($post);
          break;
        }
      }

      if ($newObject)
      {
        $topic->initsfSimpleForumPosts();
        $topic->addsfSimpleForumPost($post);
      }

      $forum = new sfSimpleForumForum();
      $forum->hydrate($rs, $startcol3);

      $newObject = true;
      foreach ($results as $temp_post)
      {
        $existing_forum = $temp_post->getsfSimpleForumForum();
        if ($existing_forum->getPrimaryKey() === $forum->getPrimaryKey())
        {
          $newObject = false;
          $existing_forum->addsfSimpleForumPost($post);
          break;
        }
      }

      if ($newObject)
      {
        $forum->initsfSimpleForumPosts();
        $forum->addsfSimpleForumPost($post);
      }

      $results[] = $post;
    }
    return $results;
  } */
}
