<?php

/**
 * PluginsfSimpleForumAbuseLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfSimpleForumAbuseLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfSimpleForumAbuseLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfSimpleForumAbuseLog');
    }
}