<?php

/**
 * PluginsfSimpleRecommandationLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfSimpleRecommandationLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfSimpleRecommandationLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfSimpleRecommandationLog');
    }
}