<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfSimpleForumForum extends BasesfSimpleForumForum
{
  public function getTopics($max = 10)
  {
    $q = $this->getTopicsCriteria();
    $q->limit($max);

    return $q->execute();
  }

  public function getTopicsPager($page = 1, $max_per_page = 10)
  {
    $q = $this->getTopicsCriteria();

    $pager = new sfDoctrinePager('sfSimpleForumTopic', $max_per_page);
    $pager->setPage($page);
    $pager->setQuery($q);
    $pager->init();

    return $pager;
  }

  public function getTopicsCriteria()
  {
    $q = Doctrine_Query::create();
    $q->from('sfSimpleForumTopic');
    $q->where('forum_id = ?', array($this->getId()));
    $q->orderBy('is_sticked DESC, updated_at DESC');

    return $q;
  }

  public function getLatestPostByQuery()
  {
    $q = Doctrine_Query::create();
    $q->from('sfSimpleForumPost');
    $q->where('forum_id = ?', array($this->getId()));
    $q->orderBy('id DESC');

    return $q->limit(1)->execute()->getFirst();
  }

  public function getLatestPost($con = null)
  {
    return $this->getsfSimpleForumPost($con);
  }

  public function getPosts($max)
  {
    return Doctrine::getTable('sfSimpleForumPost')->getForForum($this->getSlug(), $max);
  }

  public function getPostsPager($page = 1, $max_per_page = 10)
  {
    return Doctrine::getTable('sfSimpleForumPost')->getForForumPager($this->getSlug(), $page, $max_per_page);
  }

  public function updateCounts($latestReply = null, $con = null)
  {
    if($latestReply)
    {
      $this->setNbPosts(Doctrine::getTable('sfSimpleForumPost')->findByForumId($this->get('id'))->count());
      $this->setNbTopics(Doctrine::getTable('sfSimpleForumTopic')->findByForumId($this->get('id'))->count());
      $this->setLatestPostId($latestReply->getId());
      $this->setUpdatedAt($latestReply->getCreatedAt());
    }
    else
    {
      $this->setNbPosts(0);
      $this->setNbTopics(0);
      $this->setLatestPostId(null);
    }
    $this->save($con);
  }
}