<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfSimpleForumPost extends BasesfSimpleForumPost
{
  public function __toString()
  {
    return $this->getTitle();
  }

  public function getUser()
  {
    return sfSimpleForumTools::getUser($this);
  }

  public function getAuthorName()
  {
    if($this->get('user_id'))
    {
      return $this->get('sfGuardUser')->get('username');
    }
    else
    {
      return 'anonymous';
    }
  }
  
  public function getTopic()
  {
    return $this->getsfSimpleForumTopic();
  }
  
  // public function setTopicId($id)
  // {
    // if(is_int($id))
    // {
      // parent::set('topic_id', $id);
      // if( ! $this->get('id'))
      // {
        // $topic = $this->getsfSimpleForumTopic();
        // $this->setTitle($topic->getTitle());
        // $this->setForumId($topic->getForumId());
      // }
    // }
  // }
  
  // public function setsfSimpleForumTopic($title)
  // {
    // $topic = Doctrine::getTable('sfSimpleForumTopic')->findOneByTitle($title);
    // if($topic instanceOf sfSimpleForumTopic)
    // {
      // parent::set('topic_id', $topic->get('id'));
      // if( ! $this->get('id'))
      // {
        // $this->setTitle($topic->getTitle());
        // $this->setForumId($topic->getForumId());
      // }
    // }
  // }
  
  public function getPositionInTopic()
  {
    $q = Doctrine_Query::create()
            ->from('sfSimpleForumPost')
            ->select('sfSimpleForumPost.id')
            ->where('sfSimpleForumPost.topic_id = ?', array($this->getTopicId()))
            ->orderBy('created_at ASC');

    $rs = $q->execute();

    $messages = array();
    foreach($rs as $post)
    {
      $messages[] = $post->getId();
    }

    return array_search($this->getId(), $messages);
  }
  
  //public function save(Doctrine_connection $conn = null, $preserveTopic = false)
  public function save(Doctrine_Connection $conn = null)
  {
    // we don't handle this save when we load data from command line
    if( ! isset($_SERVER['REQUEST_URI']))
    {
      return parent::save($conn);
    }
    
    if(!$conn)
    {
      $conn = Doctrine_Manager::connection();
    }

    try
    {
      $conn->beginTransaction();
      
      $topic = $this->getsfSimpleForumTopic();
      if($this->isNew())
      {
        $topic->clearViews();
      }
      
      parent::save($conn);
      
      $latestPost = $topic->getLatestPostByQuery();
      if(isset($preserveTopic))
      {
        $topic->leaveUpdatedAtUnchanged();
      }
      $topic->updateReplies($latestPost, $conn);
      
      $conn->commit();
    }
    catch (Exception $e)
    {
      $conn->rollback();
      throw $e;
    }
  }

  //public function delete(Doctrine_connection $conn = null, $preserveTopic = false)
  public function delete(Doctrine_Connection $conn = null)
  {
    if(!$conn)
    {
      $conn = Doctrine_Manager::connection();
    }

    try
    {
      $conn->beginTransaction();
     
      parent::delete($conn);
      
      $topic = $this->getsfSimpleForumTopic();
      if(isset($preserveTopic))
      {
        $topic->leaveUpdatedAtUnchanged();
      }
      $latestPost = $topic->getLatestPostByQuery();
      $topic->updateReplies($latestPost, $conn);
     
      $conn->commit();
    }
    catch (Exception $e)
    {
      $conn->rollback();
      throw $e;
    }
  }
  
  public function getFeedLink()
  {
    return 'sfSimpleForum/topic?id='.$this->getTopicId().'&stripped_title='.$this->getsfSimpleForumTopic()->getSlug();
  }
  
  public function getCreationTimestamp()
  {
    return $this->getCreatedAt('U');
  }
}