<?php

/**
 * PluginsfSimpleAbuseLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfSimpleAbuseLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfSimpleAbuseLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfSimpleAbuseLog');
    }
}