<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfSimpleForumCategory extends BasesfSimpleForumCategory
{
  public function getFora()
  {
    $q = Doctrine_Query::create();
    $q->from('sfSimpleForumForum');
    $q->where('category_id = ?', $this->getId());
    $q->orderBy('rank ASC');
    
    return $q->execute();
  }
  
  public function __toString()
  {
    return $this->getName();
  }
}